# Projekt Zaliczeniowy z Numerycznej Mechaniki Płynów

## Wojciech Chlapek i Michał Walczyński

# Julia

Julia jest dość nowych językiem (9 lat) w porównaniu do Pythona (30 lat). Czerpie z niego niektóre rozwiązania składniowe, wiele funkcji nazywa się identycznie itp.

Podstawowe założenia Julii:

- prostota zapisu jak w Pythonie
- szybkość jak w C

O dziwo Julia całkiem dobrze radzi sobie z jednym i drugim. Kod w Julii, zwłaszcza w zastosowaniach numerycznych, jest często nawet bardziej czytelny niż kod w Pythonie. Jednocześnie Julia jest naprawdę dobrze zoptymalizowana, jej kod jest zazwyczaj niewiele wolniejszy od kodu C i bije na głowę natywny kod Pythona.

Szybkość kodu Julii jest znacznym ułatwieniem dla twórców bibliotek, którzy nie muszą uciekać się do kodu w C, aby uzyskać zadowalającą wydajność. W Pythonie takie rozwiązanie jest często koniecznością.

## Kompilacja JIT (*Just-in-time*)

Julia kompiluje kod do natywnego kodu maszynowego (co pozwala uzyskać bardzo dobrą wydajność) i wykorzystuje mechanizm Just-in-time, co oznacza, że kod jest kompilowany w trakcie wykonywania i to dopiero w tym momencie, w którym jest to konieczne. Przykładowo funkcje są kompilowane tuż przed ich pierwszym uruchomieniem. Z tego powodu pierwsze uruchomienie funkcji może trwać długo - etap kompilacji jest kilkustopniowy i dość skomplikowany. W zamian za to każde kolejne wywołanie będzie korzystało z już skompilowanego i zoptymalizowanego kodu, więc jeśli funkcja będzie wykorzystywana wielokrotnie, czas poświęcony na jej skompilowanie za pierwszym razem zwróci się z nawiązką.


## Ważne cechy

W Julii przyjęto następujące założenia:
* istnieją konwencje w nazewnictwie, tj:
    - funkcje z kropką w nazwie są funkcjani zwektoryzowanymi;
    - funkcje z wykrzyknikiem na końcu modyfikują przynajmniej jeden z przekazanych argumentów;
* zmienne i operatory mogą mieć _egzotyczne_ nazwy:
    - zmienne: å, æ, ð, þ, θ,
    - operatory: $\div$, $\in$, $\notin$, $\neq$, $\veebar$;
* Julia __nie jest__ zorientowana obiektowo;
* nie ma klamer w instrukcjach, ale musi się pojawić słowo `end` na końcu (z wyjątkami);
* słowo kluczowe `end` w indeksach oznacza ostatni element; 
* istnieje rozróżnienie na wektory poziome i pionowe;
* nie ma klas w rozumieniu języków obiektowo orientowanych, ale istnieją typy i struktury oraz dziedziczenie;
* nie ma wbudowanego typu listy, zamiast tego można użyć wektora;
* posiada niektóre cechy języka funkcyjnego;
* istnieje bardzo dużo typów, część nie ma odpowiednika klasy w Pythonie;
* indeksowanie zaczyna się od 1;
* przedziały (np. w wycinkach) są prawostronnie domknięte.

## Pakiety

### Instalacja

`using Pkg
Pkg.add("nazwa_pakietu")`

### Ładowanie

`using nazwa_pakietu`

In [1]:
using LinearAlgebra, NLsolve, Plots, QuadGK, DataFrames # ładowanie pakietów

┌ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
└ @ Base loading.jl:1278


## Pomoc

Wpisanie pytajnika w konsoli powoduje przejścia do manuala pomocy, w którym wpisuje się nazwę, co do której chcemy uzyskać więcej informacji (np. nazwę funkcji albo typu).

## Nazwy

W nazwach dozwolone jest spora liczba znaków Unicode'a. Byłaby to jedynie ciekawostka, gdyby nie fakt, że niektóre funkcje wbudowane korzystają z tej możliwości i faktycznie używają znaków spoza ASCII. Przykładowo:

In [2]:
2 ≤ 2

true

Wiele z takich znaków można uzyskać poprzez wpisanie znaku `\`, następnie nazwy znaku, a następnie tabulatora. Przykładowo znak `≤` można uzyskać wpisując sekwencję znaków `\le`, a następnie wciskając tabulator. Aby to działało, niezbędne jest wsparcie dla tego mechanizmu w używanym edytorze kodu. Nazwy znaków są zbieżne z komendami w $\mathrm{\LaTeX}$-u.

Nazwa nie może rozpoczynać się od cyfry. Dzięki temu można stosować zapis w rodzaju:

In [3]:
4π

12.566370614359172

Pozwala to często ominąć znak mnożenia we wzorach matematycznych.

## Typy liczbowe

### Precyzja typu stałoprzecinkowego

Domyślny typ stałoprzecinkowy to `Int64`. Jak nazwa wskazuje, ma on ograniczoną długość (64 bity), inaczej, niż w Pythonie, gdzie domyślny typ stałoprzecinkowy ma nieograniczoną precyzję. Dlatego też poniższe działanie powoduje przepełnienie:

In [4]:
2^63

-9223372036854775808

W razie potrzeby możemy użyć typu o większej długości:

In [5]:
Int128(2)^63

9223372036854775808

### Dzielenie

Istnieją różne operatory dzielenia: `/` wykonuje dzielenie zmiennoprzecinkowe, a `÷` (`\div TAB`) całkowitoliczbowe, zaś `%` modulo.

In [6]:
5 / 4

1.25

In [7]:
5 ÷ 4

1

In [8]:
5 % 5

0

## Składnia

### Operatory przypisania

Podobnie do Pythona, poza zwykłym przypisaniem do zmiennej znakiem `=` istnieją także `+=`, `-=`, `*=`, `%=`, oraz inne np. `÷=`.

### Instrukcje złożone

Instrukcje złożone (na przykład pętla `for` albo definicja funkcji `function`) kończą się słowem kluczowym `end`. Dlatego też wcięcia w takich instrukcjach są opcjonalne - zazwyczaj stosuje się je dla czytelności, jednakże nie mają one znaczenia dla parsera języka. Ponadto nie używa się dwukropka ani nawiasów klamrowych.

In [9]:
function printer()
    for i in 1:10
        print("i=", i)
        if i % 2 == 0
            println(", jest to liczba parzysta")
        else
            println(", jest to liczba nieparzysta")
        end
    end
end

printer()

i=1, jest to liczba nieparzysta
i=2, jest to liczba parzysta
i=3, jest to liczba nieparzysta
i=4, jest to liczba parzysta
i=5, jest to liczba nieparzysta
i=6, jest to liczba parzysta
i=7, jest to liczba nieparzysta
i=8, jest to liczba parzysta
i=9, jest to liczba nieparzysta
i=10, jest to liczba parzysta



### Instrukcja warunkowe

Składa się z obowiązkowego `if`, opcjonalnych klauzul `elseif` i `else` oraz obowiązkowego `end` na końcu.

## Stringi

### Indeksowanie

w Julii indeksowanie łańcuchów znaków (ale także m.in. tablic) rozpoczyna się **od 1**. Choć w stringach dozwolone są znaki Unicode, jest tu pewna pułapka: nie pod każdym indeksem kryje się poprawny znak. Jest to związane z tym, że znaki Unicode mają zmienną szerokość, i niektóre mieszczą się pod jednym indeksem, inne pod 2 lub więcej kolejnymi indeksami. Dlatego też wybierając indeks "na chybił trafił" możemy natknąć się na środek poprzedniej litery.

In [10]:
slowo = "Mimośród"
slowo[1]

'M': ASCII/Unicode U+004D (category Lu: Letter, uppercase)

In [11]:
slowo[5] # uwaga Char

'ś': Unicode U+015B (category Ll: Letter, lowercase)

In [12]:
slowo[6]

LoadError: StringIndexError("Mimośród", 6)

### Interpolacja

W Julii łatwo możemy umieścić w stringu wartość wyrażenia. Wystarczy w tym celu użyć znaku `$`, a następnie wpisać wyrażenie.

In [13]:
x = 125
println("Zmienna ma wartość $x")

Zmienna ma wartość 125


Jeśli to wyrażenie jest bardziej skomplikowane niż sama nazwa zmiennej, zapewne konieczne będzie umieszczenie wyrażenia w nawiasach:

In [14]:
x = 4
y = 23
z = 0.4

"Wartość bardziej skomplikowanego wyrażenia: $(x * y + z)"

"Wartość bardziej skomplikowanego wyrażenia: 92.4"

### Zwielokrotnienie

Służy do tego operator `^`:

In [15]:
"abc" ^ 3

"abcabcabc"

### Konkatenacja

Łączenie stringów wykonuje się operatorem `*`:

In [16]:
poczatek = "Ala"
koniec = " ma kota"
poczatek * koniec

"Ala ma kota"

### Niezmienność

Podobnie jak Pythonie, stringów nie można modyfikować:

In [17]:
slowo = "Jurek"
slowo[1] = "M"

LoadError: MethodError: no method matching setindex!(::String, ::String, ::Int64)

Jednakże taki zapis działa:

In [18]:
imie = "Grzegorz"
imie *= " Brzęczyszczykiewicz"

"Grzegorz Brzęczyszczykiewicz"

Jest to związane z tym, że w rzeczywistości tworzony jest nowy string na podstawie starego, i ten nowy jest przypisywany do zmiennej `imie`.

## Struktury

### Krotki

Podobnie jak w Pythonie, krotki są niezmienne i mogą przechowywać elementy różnych typów.

In [19]:
a = (1, true, 'ç', "ñ")
b = 1, true, 'ç', "ñ"

println("a = $a\nb = $b") # dolar w napisach pozwala na wykorzystanie zmiennej

a = (1, true, 'ç', "ñ")
b = (1, true, 'ç', "ñ")


In [20]:
typeof(a)

Tuple{Int64,Bool,Char,String}

In [21]:
c, d = (1im, nothing)

println("c = $c\nd = $d") # \n znak nowego wiersza, nothing odpowiednikiem None w Pythonie

c = 0 + 1im
d = nothing


Warto zwrócić uwagę, że `im` to jednostka zespolona.

### Słowniki

Literał do tworzenia słownika:

In [22]:
A = Dict([("a", 1), ("b", 2)])

Dict{String,Int64} with 2 entries:
  "b" => 2
  "a" => 1

Alternatywnie zamiast zapisu `"nazwa"` można używać `:nazwa`:

In [23]:
B = Dict(:a => 1, :b => 2)

Dict{Symbol,Int64} with 2 entries:
  :a => 1
  :b => 2

In [24]:
A["a"]

1

In [25]:
B[:b]

2

## Funkcje

### Multiple dispatch

W Julii nie ma metod w rozumieniu języków obiektowo orientowanych. Nie jest więc również używana typowa dla takich języków składnia `obiekt.metoda(argumenty)`. Mianem *metody* nazywa się implementację funkcji o określonej nazwie. Dozwolonych jest wiele metod tej samej funkcji - mogą one koegzystować, pod warunkiem, że ich sygnatury nie są identyczne.

In [26]:
function foo(x::Int, y::String)
    println(y^x)
end

function foo(y::String, x::Int=0)
    println(y * " + " * string(x))
end

foo (generic function with 3 methods)

Typ można wyspecyfikować za pomocą operatora `::` (nie jest to obowiązkowe). Dodatkowo argumentom można ustawić domyślne wartości.

Mechanizm, który decyduje, która implementacja funkcji zostanie uruchomiona na potrzeby konkretnych argumentów nazywa się *Multiple Dispatch* i jest jedną z kluczowych cech języka Julia. Mechanizm ten jest bardzo szybki, do tego daje większą elastyczność niż metody z obiektowych języków programowania (co częściowo widać na poniższym przykładzie):

In [27]:
foo(5, "wiele")
foo("spam", 5)
foo("test")

wielewielewielewielewiele
spam + 5
test + 0


Typy obiektów, na jakich będzie pracować dana funkcja, nie muszą jeszcze istnieć w momencie jej tworzenia, a ponadto nie ma obowiązku tworzenia wszystkich metod danej funkcji jednocześnie. Można na przykład dodać metodę do istniejącej funkcji wbudowanej, tak, żeby obsłużyć własne typy bądź zmienić dla wybranych typów domyślne zachowanie.

### Wartość zwracana

Wartość zwracaną funkcji można jawnie określić słowem kluczowym `return`. Jest ono jednak opcjonalne, i jeśli nie występuje, wartością zwracaną funkcji jest wartość ostatniego wyrażenia w tej funkcji:

In [28]:
function average(x, y)
    (x + y) / 2
end

average (generic function with 1 method)

In [29]:
average(2, 5)

3.5

Alternatywnie można funkcję zdefiniować tak (tzw. jednolinijkowa notacja):

In [30]:
average(x, y) = (x +y)/2

average (generic function with 1 method)

In [31]:
average(2, 5)

3.5

Jeśli nie chcemy, żeby funkcja zwracała cokolwiek (a ostatnie wyrażenie zwraca wartość), możemy użyć `return nothing`:

In [32]:
function do_nothing(x, y)
    x * y
    return nothing
end

do_nothing (generic function with 1 method)

In [33]:
x = do_nothing(5, 6)
println(x)

nothing


### Wektoryzacja

Aby zaaplikować funkcję do wszystkich elementów danego obiektu iterowalnego (np. wektora) można użyć składni z kropką: `nazwafunkcji.(kolekcja)`.

In [34]:
function square(x)
    return x ^ 2
end

square (generic function with 1 method)

In [35]:
v = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [36]:
square.(v)

3-element Array{Int64,1}:
 1
 4
 9

Bez zapisu z kropką to nie zadziała:

In [37]:
square(v)

LoadError: MethodError: no method matching ^(::Array{Int64,1}, ::Int64)
Closest candidates are:
  ^(!Matched::Missing, ::Integer) at missing.jl:155
  ^(!Matched::Missing, ::Number) at missing.jl:115
  ^(!Matched::Irrational{:ℯ}, ::Integer) at mathconstants.jl:91
  ...

Co więcej, można tego rozwiązania także użyć w przypadku funkcji przyjmujących więcej niż 1 argument:

In [38]:
function funkcja(x, y)
    z = (x+y)*x*y
    return z
end

funkcja (generic function with 1 method)

In [39]:
funkcja.([1,2], [2,3]) # bardzo prosta modyfikacja

2-element Array{Int64,1}:
  6
 30

Funkcje mogą zwracać więcej niż jedną wartość używając krotki:

In [40]:
# using QuadGK
f(x) = exp(-x) * cos(x)
quadgk(f, 0, pi)

(0.5216069591318861, 4.937072972666101e-11)

## Tensory

Julia nie ma oddzielnego typu wbudowanego dla tablic jednowymiarowych - zamiast tego używa się tensora (odpowiednika `numpy.array`). W szczególności więc jednowymiarowy tensor jest wektorem.

Tensor może przechowywać wyłącznie wartości określonego typu. W szczególności typem tym może być `Any` - wtedy przechowywane wartości mogą być dowolnego typu. Zazwyczaj jednak korzysta się z bardziej specyficznego typu (np. `Float64`), co pozwala Julii zoptymalizować kod.

### Tworzenie wektorów

Literał na utworzenie wektora:

In [41]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

`Array{Int64,1}` informuje nas o tym, że mamy do czynienia z tensorem przechowującym typ `Int64` i wymiarze 1 (czyli jest to wektor). Domyślnie w Julii wektory są pionowe.

W tym przykładzie jedna z liczb jest typu zmiennoprzecinkowego, więc nastąpi konwersja wszystkich liczb na typ zmiennoprzecinkowy:

In [42]:
x = [1, 2.0, 3]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

Alternatywne sposoby utworzenia wektora z wykorzystaniem wycinka:

In [43]:
a = collect(1:3) # odpowienik range Pythona, range w Julii jest odpowiedniki np.linspace

3-element Array{Int64,1}:
 1
 2
 3

In [44]:
b = [1:3...]

3-element Array{Int64,1}:
 1
 2
 3

Odpowiednik listy składanej (list comprehension) Pythona:

In [45]:
c = [i for i in 1:3] # tu właśnie nie trzeba end

3-element Array{Int64,1}:
 1
 2
 3

### Tworzenie macierzy

Zapisując literał macierzy nie używamy przecinków - kolejne elementy w danym wierszu oddzielamy spacją, a przejście do nowego wiersza robi się znakiem nowej linii lub średnikiem.

In [46]:
A = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

Uwaga: pod zmienną `e` znajdzie się jednowierszowa macierz, nie wektor. Można się o tym przekonać, patrząc na wymiar tej macierzy (`2`).

In [47]:
e = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

Uwaga: poniższy zapis produkuje wektor, nie jednokolumnową macierz:

In [48]:
v = [1; 2; 3]

3-element Array{Int64,1}:
 1
 2
 3

Jest to swoista niekonsekwencja względem poprzedniego przykładu, gdzie otrzymaliśmy jednowierszową macierz, a nie wektor (poziomy lub pionowy).

Uwaga: domyślnie macierz w Julii jest przechowywana "kolumnami" (odwrotnie niż w NumPy), co jest istotne np. w przypadku indeksowania spłaszczonej macierzy lub gdy używamy funkcji `reshape`:

In [49]:
reshape([1, 2, 3, 4, 5, 6, 7, 8], 4, 2)

4×2 Array{Int64,2}:
 1  5
 2  6
 3  7
 4  8

### Transpozycja

Transpozycję wykonuje się znakiem `'` (pojedynczy apostrof) po nazwie macierzy.

In [50]:
A' # transpozycja

3×2 Adjoint{Int64,Array{Int64,2}}:
 1  4
 2  5
 3  6

Transpozycja działa również na wektorach: zamienia wektor pionowy (domyślny) na poziomy i odwrotnie.

In [51]:
v'

1×3 Adjoint{Int64,Array{Int64,1}}:
 1  2  3

In [52]:
v''

3-element Array{Int64,1}:
 1
 2
 3

### Mnożenie macierzowe



Julia operatorem `*` wykonuje na tensorach mnożenie macierzowe:

In [53]:
B = A * a

2-element Array{Int64,1}:
 14
 32

Pilnuje także, aby wymiary przy mnożeniu się zgadzały:

In [54]:
C = a * A 

LoadError: DimensionMismatch("matrix A has dimensions (3,1), matrix B has dimensions (2,3)")

In [55]:
D = a * e

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

In [56]:
E = e * a

1-element Array{Int64,1}:
 14

### Operacje na macierzy / poszczególnych elementach

W ogólności operatory Julii wykonują operacje na całych tensorach, a nie na odpowiadających sobie pojedynczych elementach z macierzy (jak w bibliotece `NumPy`).

In [57]:
A + 1

LoadError: MethodError: no method matching +(::Array{Int64,2}, ::Int64)
For element-wise addition, use broadcasting with dot syntax: array .+ scalar
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(!Matched::Missing, ::Number) at missing.jl:115
  +(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:116
  ...

Jeśli oczekujemy, aby operator zadziałał na poszczególnych elementach zamiast na całości, możemy użyć składni wektoryzacji, czyli znaku kropki przez operatorem:

In [58]:
A .+ 1

2×3 Array{Int64,2}:
 2  3  4
 5  6  7

Tutaj również mamy podniesienie całej macierzy do kwadratu, a nie jej poszczególnych elementów:

In [59]:
G = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [60]:
G^2

3×3 Array{Int64,2}:
  30   36   42
  66   81   96
 102  126  150

Jeśli chcemy podnieść poszczególne elementy do kwadratu, możemy użyć zwektoryzowanego operatora:

In [61]:
G .^2 #inny wynik, bo to jest podnoszenie elementów do kwadratu

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81

Julia potrafi poprawnie obliczyć wartość wyrażenia $\mathrm{e}^\mathbf{A}$, gdzie $A$ jest macierzą.

In [62]:
exp(G) # jak wcześniej

3×3 Array{Float64,2}:
 1.11891e6  1.37482e6  1.63072e6
 2.53388e6  3.11342e6  3.69295e6
 3.94886e6  4.85201e6  5.75517e6

Nie jest to to samo, co liczenie "element po elemencie":

In [63]:
exp.(G) # bo to jest liczenie eksponenty poszczególnych elementów

3×3 Array{Float64,2}:
    2.71828     7.38906    20.0855
   54.5982    148.413     403.429
 1096.63     2980.96     8103.08

### Indeksowanie

Poniższe przykłady odnoszą się do macierzy, jednakże w analogiczny sposób wykonuje się indeksowanie w większej liczbie wymiarów niż 2.

In [64]:
G

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

Aby wybrać konkretny element macierzy stosujemy notację `Macierz[wiersz, kolumna]`:

In [65]:
G[2, 3]

6

Możemy wybrać więcej, niż jeden wiersz (lub kolumnę):

In [66]:
G[[1,2], 3]

2-element Array{Int64,1}:
 3
 6

Ostatni element w danym wymiarze jest dostępny za pomocą słowa kluczowego `end`:

In [67]:
G[end, 1]

7

Jeśli chcemy wybrać wszystkie elementy z danego wymiaru, wpisujemy `:`. Przykładowo poniżej wybranie elementów z wszystkich wierszy drugiej kolumny:

In [68]:
G[:, 2] # druga kolumna

3-element Array{Int64,1}:
 2
 5
 8

Wybranie wszystkich elementów z drugiego wiersza:

In [69]:
G[2, :] # drugi wiersz

3-element Array{Int64,1}:
 4
 5
 6

Uwaga: wybierając wszystkie elementy z danego wiersza bądź danej kolumny następuje redukcja otrzymujemy w obu przypadkach wektor pionowy.

### Modyfikacja tensora

Domyślnie tensory można modyfikować:

In [70]:
G[1,1] = 0 # podmiana

0

In [71]:
G

3×3 Array{Int64,2}:
 0  2  3
 4  5  6
 7  8  9

Element na koniec wektora można dodać funkcją `append!`:

In [72]:
b

3-element Array{Int64,1}:
 1
 2
 3

In [73]:
append!(b, 4) # dodanie 4 do wektora

4-element Array{Int64,1}:
 1
 2
 3
 4

Wstawienie elementu na innej pozycji niż ostatnia można zrobić funkcją `insert!`:

In [74]:
insert!(b, 3, 0)

5-element Array{Int64,1}:
 1
 2
 0
 3
 4

Iloczyn skalarny między wektorami można policzyć za pomocą funkcji `dot` z pakietu `LinearAlgebra` lub operatora ⋅ (`\cdot TAB`):

In [75]:
# using LinearAlgebra

println(dot([1 2], [3 4]))
println([1, 2] ⋅ [3, 4])

11
11


## Wycinek

Wycinek jest obiektem, który może posłużyć do generacji ciągu liczb. Wycinka można także użyć, aby pobrać fragment tensora, stringa itp.

Składnia wycinka to `początek:koniec` (koniec włącznie, inaczej, niż w funkcji `range` Pythona).

In [76]:
1:10

1:10

Dla oszczędności pamięci elementy wycinka nie są generowane, dopóki nie jest to konieczne. Zebrać w wektor elementy generowane przez wycinek można przy pomocy funkcji `collect`:

In [77]:
a = collect(0:20)

21-element Array{Int64,1}:
  0
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20

Opcjonalnie można użyć alternatywnego zapisu z wielkością kroku `początek:krok:koniec` (domyślnie krok ma wartość 1). Tutaj zastosowanie do pobrania co czwartego elementu wektora:

In [78]:
a[1:4:end]

6-element Array{Int64,1}:
  0
  4
  8
 12
 16
 20

W powyższej instrukcji widać również zastosowanie słowa kluczowego `end`, oznaczającego ostatni indeks tego wektora.

Indeksowanie stringa jest analogiczne do indeksowania wektora (choć, jak to było już wcześniej wspomniane, niektóre litery znajdują się pod więcej niż jednym indeksem). Tutaj także można użyć wycinka, aby uzyskać podciąg znaków:

In [79]:
slowo = "Autobus"
slowo[2:5]

"utob"

In [80]:
slowo[1:end-1]

"Autobu"

## Elementy funkcyjności

Operatory można wywołać tak, jak zwykłe funkcje:

In [81]:
+(1,4,6)

11

In [82]:
<(4, 7)

true

Możliwość ta istnieje nawet dla zwektoryzowanych wersji operatorów:

In [83]:
.≤([4,2], [5, 0]) 

2-element BitArray{1}:
 1
 0

## Rozwiązywanie równań

Wbudowanym sposobem rozwiązywania liniowych układów równań jest użycie operatora `\`.

### Przykład 1

$\left\lbrace{\begin{align} x+ y +z = 6\\ x+y = 3\\ x +z = 4\end{align}}\right.$

Zapis macierzowy

$\begin{bmatrix} 1 & 1 & 1 \\ 1 & 1 & 0 \\ 1 & 0 & 1\\ \end{bmatrix} \begin{bmatrix} x\\ y \\ z \end{bmatrix} = \begin{bmatrix} 6\\ 3\\ 4\\ \end{bmatrix}$

In [84]:
[1 1 1; 1 1 0; 1 0 1] \ [6;3;4]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

Otrzymane rozwiązanie to:

$\left\lbrace\begin{align} x = 1\\ y = 2\\ z = 3 \end{align}\right.$

### Przykład 2

$\left\lbrace{\begin{align}  x^2-7+5x = y\\4y +8x = -21\end{align}}\right.$

Rozwiązywanie układu równań nieliniowych:

In [85]:
# using NLsolve

function f!(F, v) # tu ważna konwencja z wykrzyknikiem
    x, y = v
    F[1] = y - x^2 -7 + 5*x
    F[2] = 4*y - 8*x + 21
end

res =  nlsolve(f!, [5.0; 5.0]) # uwaga: musi być Float, Int wyrzuca błąd

Results of Nonlinear Solver Algorithm
 * Algorithm: Trust-region with dogleg and autoscaling
 * Starting Point: [5.0, 5.0]
 * Zero: [3.5000915527459067, 1.7501831054918187]
 * Inf-norm of residuals: 0.000000
 * Iterations: 14
 * Convergence: true
   * |x - x'| < 0.0e+00: false
   * |f(x)| < 1.0e-08: true
 * Function Calls (f): 15
 * Jacobian Calls (df/dx): 15

In [86]:
res.zero

2-element Array{Float64,1}:
 3.5000915527459067
 1.7501831054918187

Otrzymane rozwiązanie to:

$\left\lbrace\begin{gather} x \approx 3,\!50\\ y \approx 1,\!75\end{gather}\right.$

## Ramki/tablice danych (*Data frame*)

Do korzystania z ramek danych potrzebny jest pakiet `DataFrames`.

In [87]:
using DataFrames

### Tworzenie ramki

In [88]:
chemtabla = DataFrame(  LiczbaAtomowa       =   [1,   2,    6,    8,    26    ],
                     Nazwa        =   ["Wodór",   "Hel",   "Węgiel",   "Tlen",   "Żelazo"   ],
                     MasaAtomowa =   [1.0079,    4.0026,  12.0107, 15.9994, 55.845   ],
                     Symbol       =   ["H",    "He",    "C",    "O",  "Fe"  ],
                     Odkryty  =   [1776,   1895,    0,    1774,    missing    ])

5×5 DataFrame
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol  Odkryty 
     │ Int64          String  Float64      String  Int64?  
─────┼─────────────────────────────────────────────────────
   1 │             1  Wodór        1.0079  H          1776
   2 │             2  Hel          4.0026  He         1895
   3 │             6  Węgiel      12.0107  C             0
   4 │             8  Tlen        15.9994  O          1774
   5 │            26  Żelazo      55.845   Fe      missing 

### Operacje na ramce

#### Opis kolumn
Funkcja `describe` zwraca podstawowe informacje o poszczególnych kolumnach (jest zwektoryzowana!):

In [89]:
describe(chemtabla)

5×7 DataFrame
 Row │ variable       mean     min     median   max     nmissing  eltype       ⋯
     │ Symbol         Union…   Any     Union…   Any     Int64     Type         ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ LiczbaAtomowa  8.6      1       6.0      26             0  Int64        ⋯
   2 │ Nazwa                   Hel              Żelazo         0  String
   3 │ MasaAtomowa    17.7731  1.0079  12.0107  55.845         0  Float64
   4 │ Symbol                  C                O              0  String
   5 │ Odkryty        1361.25  0       1775.0   1895           1  Union{Missin ⋯
                                                                1 column omitted

### Dostęp do kolumn

Aby uzyskać dostęp do jednej kolumny można użyć notacji `nazwa_ramki.nazwa_kolumny`:

In [90]:
chemtabla.Symbol # wynik będzie wektorem

5-element Array{String,1}:
 "H"
 "He"
 "C"
 "O"
 "Fe"

można również uzyskać dostęp w następujący sposób:

In [91]:
chemtabla[:, :Symbol] # wynik także wektore

5-element Array{String,1}:
 "H"
 "He"
 "C"
 "O"
 "Fe"

Do większej liczby kolumn też można uzyskać dostęp

In [92]:
chemtabla[:, [:Nazwa, :Symbol]] # przecinek obowiązkowy

5×2 DataFrame
 Row │ Nazwa   Symbol 
     │ String  String 
─────┼────────────────
   1 │ Wodór   H
   2 │ Hel     He
   3 │ Węgiel  C
   4 │ Tlen    O
   5 │ Żelazo  Fe

#### Wykluczanie kolumn

Operator `Not()` powoduje, że kolumn o podanym numerze nie będzie.

In [93]:
chemtabla[:, Not(5)]

5×4 DataFrame
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol 
     │ Int64          String  Float64      String 
─────┼────────────────────────────────────────────
   1 │             1  Wodór        1.0079  H
   2 │             2  Hel          4.0026  He
   3 │             6  Węgiel      12.0107  C
   4 │             8  Tlen        15.9994  O
   5 │            26  Żelazo      55.845   Fe

Można też po nazwach:

In [94]:
chemtabla[:, Not(:Odkryty)]

5×4 DataFrame
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol 
     │ Int64          String  Float64      String 
─────┼────────────────────────────────────────────
   1 │             1  Wodór        1.0079  H
   2 │             2  Hel          4.0026  He
   3 │             6  Węgiel      12.0107  C
   4 │             8  Tlen        15.9994  O
   5 │            26  Żelazo      55.845   Fe

### Operacje na wierszach

Filtruje się analogicznie do macierzy, dodatkowo można wykorzystać `Not`.

In [95]:
chemtabla[2:3, :]

2×5 DataFrame
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol  Odkryty 
     │ Int64          String  Float64      String  Int64?  
─────┼─────────────────────────────────────────────────────
   1 │             2  Hel          4.0026  He         1895
   2 │             6  Węgiel      12.0107  C             0

In [96]:
chemtabla[Not(end), :]

4×5 DataFrame
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol  Odkryty 
     │ Int64          String  Float64      String  Int64?  
─────┼─────────────────────────────────────────────────────
   1 │             1  Wodór        1.0079  H          1776
   2 │             2  Hel          4.0026  He         1895
   3 │             6  Węgiel      12.0107  C             0
   4 │             8  Tlen        15.9994  O          1774

In [97]:
chemtabla[chemtabla.MasaAtomowa .< 13, :]

3×5 DataFrame
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol  Odkryty 
     │ Int64          String  Float64      String  Int64?  
─────┼─────────────────────────────────────────────────────
   1 │             1  Wodór        1.0079  H          1776
   2 │             2  Hel          4.0026  He         1895
   3 │             6  Węgiel      12.0107  C             0

### Modyfikacja ramki

Wynik można uzyskać na parę sposób

In [98]:
chemtabla.MasaNukleonu = chemtabla.MasaAtomowa./chemtabla.LiczbaAtomowa

5-element Array{Float64,1}:
 1.0079
 2.0013
 2.0017833333333335
 1.999925
 2.147884615384615

In [99]:
chemtabla

5×6 DataFrame
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol  Odkryty  MasaNukleonu 
     │ Int64          String  Float64      String  Int64?   Float64      
─────┼───────────────────────────────────────────────────────────────────
   1 │             1  Wodór        1.0079  H          1776       1.0079
   2 │             2  Hel          4.0026  He         1895       2.0013
   3 │             6  Węgiel      12.0107  C             0       2.00178
   4 │             8  Tlen        15.9994  O          1774       1.99992
   5 │            26  Żelazo      55.845   Fe      missing       2.14788

Można i w taki sposób:

In [100]:
chemtabla[!, :MasaNukleonu] = chemtabla.MasaAtomowa./chemtabla.LiczbaAtomowa

5-element Array{Float64,1}:
 1.0079
 2.0013
 2.0017833333333335
 1.999925
 2.147884615384615

### Agregowanie

Aby użyć funkcji agregującej, należy na początku użyć funkcji `combine`:

In [101]:
combine(chemtabla, [:LiczbaAtomowa, :MasaAtomowa] .=> sum) # tak wektoryzacja i to działa trochę słownikowo

1×2 DataFrame
 Row │ LiczbaAtomowa_sum  MasaAtomowa_sum 
     │ Int64              Float64         
─────┼────────────────────────────────────
   1 │                43          88.8656

Można także właczyć grupowanie. W tym celu będzie dodana nowa kolumna `masywnyNukleon`.

In [102]:
chemtabla[!, :MasywnyNukleon] = ifelse.(chemtabla.MasaNukleonu .> 2, "tak", "nie")

5-element Array{String,1}:
 "nie"
 "tak"
 "tak"
 "nie"
 "tak"

In [103]:
chemtabla

5×7 DataFrame
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol  Odkryty  MasaNukleonu  Masy ⋯
     │ Int64          String  Float64      String  Int64?   Float64       Stri ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │             1  Wodór        1.0079  H          1776       1.0079   nie  ⋯
   2 │             2  Hel          4.0026  He         1895       2.0013   tak
   3 │             6  Węgiel      12.0107  C             0       2.00178  tak
   4 │             8  Tlen        15.9994  O          1774       1.99992  nie
   5 │            26  Żelazo      55.845   Fe      missing       2.14788  tak  ⋯
                                                                1 column omitted

Grupowanie odbywa się przy użyciu `groupby`:

In [104]:
ct = groupby(chemtabla, :MasywnyNukleon)

GroupedDataFrame with 2 groups based on key: MasywnyNukleon
First Group (2 rows): MasywnyNukleon = "nie"
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol  Odkryty  MasaNukleonu  Masy ⋯
     │ Int64          String  Float64      String  Int64?   Float64       Stri ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │             1  Wodór        1.0079  H          1776       1.0079   nie  ⋯
   2 │             8  Tlen        15.9994  O          1774       1.99992  nie
                                                                1 column omitted
⋮
Last Group (3 rows): MasywnyNukleon = "tak"
 Row │ LiczbaAtomowa  Nazwa   MasaAtomowa  Symbol  Odkryty  MasaNukleonu  Masy ⋯
     │ Int64          String  Float64      String  Int64?   Float64       Stri ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │             2  Hel          4.0026  He         1895       2.0013   tak  ⋯
   2 │             6  Węgiel      12.0107  C             0       2.00178  tak
   3 │            26  Żelazo      55.845   Fe      missing       2.14788  tak
                                                                1 column omitted

Dalej już jak wcześniej:

In [105]:
combine(ct, [:LiczbaAtomowa, :MasaAtomowa] .=> sum)

2×3 DataFrame
 Row │ MasywnyNukleon  LiczbaAtomowa_sum  MasaAtomowa_sum 
     │ String          Int64              Float64         
─────┼────────────────────────────────────────────────────
   1 │ nie                             9          17.0073
   2 │ tak                            34          71.8583